# Generated by Django 4.2.2 on 2023-07-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Noticias',
        ),
    ]
